"""
Assertion Generator (new capability #14).

Infers SystemVerilog Assertions from what the rest of the analysis pipeline
already knows (FSM legality from ``fsm_analyzer``, counter monotonicity from
``counter_analyzer``, reset behavior from the Knowledge Graph) and emits them
as a *separate* `.sva`/bind file per module - RTL source is never modified.
"""
from __future__ import annotations

import os

from core.knowledge_graph import ProjectKnowledgeGraph
from core.schemas import (
    AssertionSuite,
    CounterAnalysisReport,
    FSMAnalysisReport,
    GeneratedAssertion,
)


def _reset_assertions(module: str, kg: ProjectKnowledgeGraph) -> list[GeneratedAssertion]:
    out = []
    for ab in kg.always_blocks_for(module):
        if not ab.reset_signal:
            continue
        for reg in ab.written_regs:
            name = f"a_{module}_{reg}_reset"
            sva = (
                f"property {name}_p;\n"
                f"  @(posedge {ab.clock_signal or 'clk'}) {ab.reset_signal} |-> ##1 "
                f"{reg} == '0;\n"
                f"endproperty\n"
                f"{name}: assert property({name}_p);"
            )
            out.append(GeneratedAssertion(
                name=name, module=module, kind="reset", sva_text=sva,
                rationale=f"Register '{reg}' is reset by '{ab.reset_signal}'; assert it "
                          f"lands at 0 the cycle after reset asserts.",
            ))
    return out


def _fsm_assertions(fsm_report: FSMAnalysisReport) -> list[GeneratedAssertion]:
    out = []
    for fsm in fsm_report.fsms:
        if not fsm.states:
            continue
        legal = " || ".join(f"{fsm.state_signal} == {s}" for s in fsm.states)
        name = f"a_{fsm.module}_{fsm.state_signal}_legal"
        sva = (
            f"property {name}_p;\n"
            f"  @(posedge clk) ({legal});\n"
            f"endproperty\n"
            f"{name}: assert property({name}_p);"
        )
        out.append(GeneratedAssertion(
            name=name, module=fsm.module, kind="fsm_legality", sva_text=sva,
            rationale=f"State signal '{fsm.state_signal}' must always hold one of its "
                      f"{len(fsm.states)} declared/observed state value(s).",
        ))
    return out


def _counter_assertions(counter_report: CounterAnalysisReport) -> list[GeneratedAssertion]:
    out = []
    for c in counter_report.counters:
        if not c.has_enable:
            continue  # unconditional counters are trivially monotonic; less interesting
        name = f"a_{c.module}_{c.signal}_monotonic"
        sva = (
            f"property {name}_p;\n"
            f"  @(posedge clk) ({c.signal} != '1) |=> ({c.signal} >= $past({c.signal}));\n"
            f"endproperty\n"
            f"{name}: assert property({name}_p);"
        )
        out.append(GeneratedAssertion(
            name=name, module=c.module, kind="counter_monotonic", sva_text=sva,
            rationale=f"Counter '{c.signal}' should be non-decreasing between enabled "
                      f"increments (excluding wraparound at max value).",
        ))
    return out


def generate(
    kg: ProjectKnowledgeGraph,
    fsm_report: FSMAnalysisReport,
    counter_report: CounterAnalysisReport,
    modules: list[str],
    out_dir: str,
) -> list[AssertionSuite]:
    """Build one ``AssertionSuite`` (and one .sva file) per module that has at
    least one inferrable assertion, writing files under ``out_dir/assertions``."""
    os.makedirs(os.path.join(out_dir, "assertions"), exist_ok=True)
    suites: dict[str, list[GeneratedAssertion]] = {m: [] for m in modules}

    for a in _fsm_assertions(fsm_report):
        suites.setdefault(a.module, []).append(a)
    for a in _counter_assertions(counter_report):
        suites.setdefault(a.module, []).append(a)
    for module in modules:
        suites.setdefault(module, []).extend(_reset_assertions(module, kg))

    out: list[AssertionSuite] = []
    for module, assertions in suites.items():
        if not assertions:
            continue
        path = os.path.join(out_dir, "assertions", f"{module}_assertions.sva")
        with open(path, "w") as f:
            f.write(f"// Auto-generated SystemVerilog assertions for module '{module}'.\n")
            f.write("// Generated by SiliconPilot's Assertion Generator; does not modify RTL.\n\n")
            for a in assertions:
                f.write(f"// {a.rationale}\n{a.sva_text}\n\n")
        out.append(AssertionSuite(module=module, assertions=assertions, file_path=path))
    return out
